force-app/main/default/objects/cg_Quote__c/cg_Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cg_Quote__c/fields/cg_Quote_number__c.field-meta.xml
<CustomField>
    <fullName>cg_Quote_number__c</fullName>
    <displayFormat>Q -{0000}</displayFormat>
    <label>Quote number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/ProductPageWithQuoteController.cls
/**
 * Controller for the ProductPageWithQuote Visualforce page
 */
public with sharing class ProductPageWithQuoteController {
    public String quoteId { get; set; }
    public String quoteNumber { get; set; }
    
    public ProductPageWithQuoteController() {
        // Get the quoteId from the URL parameters
        quoteId = ApexPages.currentPage().getParameters().get('quoteId');
        
        // Get the quote number if quoteId is provided
        if (quoteId != null) {
            cg_Quote__c quote = [SELECT cg_Quote_number__c FROM cg_Quote__c WHERE Id = :quoteId LIMIT 1];
            if (quote != null) {
                quoteNumber = quote.cg_Quote_number__c;
            }
        }
    }
}